version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: scryme-chat-pg
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-main}
    ports:
      - '54321:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-main}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  rustfs:
    image: rustfs/rustfs:latest
    container_name: scryme-chat-rustfs
    restart: always
    environment:
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY:-rustfsadmin}
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY:-rustfsadmin}
    ports:
      - '9000:9000'
    volumes:
      - rustfs_data:/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: scryme-chat-redis
    restart: always
    command: >
      sh -c "
        if [ -n \"$REDIS_PASSWORD\" ]; then
          exec redis-server --requirepass \"$REDIS_PASSWORD\"
        else
          exec redis-server --requirepass myredispassword
        fi
      "
    ports:
      - '6479:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: >
        sh -c "
          if [ -n \"$REDIS_PASSWORD\" ]; then
            redis-cli -a \"$REDIS_PASSWORD\" ping
          else
            redis-cli -a myredispassword ping
          fi
        "
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  rustfs_data:

networks:
  app-network:
    driver: bridge
