/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/rider-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dms` | `/dms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workspaces` | `/workspaces`; params?: Router.UnknownInputParams; } | { pathname: `/auth/qr-scanner`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]/info`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]/thread/[threadId]`, params: Router.UnknownInputParams & { id: string | number;threadId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/rider-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dms` | `/dms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/workspaces` | `/workspaces`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/qr-scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/chat/[id]/info`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/chat/[id]/thread/[threadId]`, params: Router.UnknownOutputParams & { id: string;threadId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/rider-profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/channels${`?${string}` | `#${string}` | ''}` | `/channels${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dms${`?${string}` | `#${string}` | ''}` | `/dms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/workspaces${`?${string}` | `#${string}` | ''}` | `/workspaces${`?${string}` | `#${string}` | ''}` | `/auth/qr-scanner${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/rider-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/channels` | `/channels`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dms` | `/dms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/workspaces` | `/workspaces`; params?: Router.UnknownInputParams; } | { pathname: `/auth/qr-scanner`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/chat/${Router.SingleRoutePart<T>}/info${`?${string}` | `#${string}` | ''}` | `/chat/${Router.SingleRoutePart<T>}/thread/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]/info`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/chat/[id]/thread/[threadId]`, params: Router.UnknownInputParams & { id: string | number;threadId: string | number; } };
    }
  }
}
